package usd.jedzius.crispychannels.protocol;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: UserTransferPayload.proto
// Protobuf Java Version: 4.26.0-rc2

public final class UserTransferPayload {
  private UserTransferPayload() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 26,
      /* patch= */ 0,
      /* suffix= */ "-rc2",
      UserTransferPayload.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserConnectServerPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:UserConnectServerPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>int32 serverId = 2;</code>
     * @return The serverId.
     */
    int getServerId();

    /**
     * <code>.Location location = 3;</code>
     * @return Whether the location field is set.
     */
    boolean hasLocation();
    /**
     * <code>.Location location = 3;</code>
     * @return The location.
     */
    UserTransferPayload.Location getLocation();
    /**
     * <code>.Location location = 3;</code>
     */
    UserTransferPayload.LocationOrBuilder getLocationOrBuilder();

    /**
     * <code>string gamemode = 4;</code>
     * @return The gamemode.
     */
    java.lang.String getGamemode();
    /**
     * <code>string gamemode = 4;</code>
     * @return The bytes for gamemode.
     */
    com.google.protobuf.ByteString
        getGamemodeBytes();

    /**
     * <code>int32 slot = 5;</code>
     * @return The slot.
     */
    int getSlot();

    /**
     * <code>int32 food = 6;</code>
     * @return The food.
     */
    int getFood();

    /**
     * <code>int32 health = 7;</code>
     * @return The health.
     */
    int getHealth();

    /**
     * <code>bytes inventory = 8;</code>
     * @return The inventory.
     */
    com.google.protobuf.ByteString getInventory();

    /**
     * <code>bytes enderchest = 9;</code>
     * @return The enderchest.
     */
    com.google.protobuf.ByteString getEnderchest();

    /**
     * <code>bytes potionEffects = 10;</code>
     * @return The potionEffects.
     */
    com.google.protobuf.ByteString getPotionEffects();
  }
  /**
   * Protobuf type {@code UserConnectServerPayload}
   */
  public static final class UserConnectServerPayload extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:UserConnectServerPayload)
      UserConnectServerPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "-rc2",
        UserConnectServerPayload.class.getName());
    }
    // Use UserConnectServerPayload.newBuilder() to construct.
    private UserConnectServerPayload(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private UserConnectServerPayload() {
      uuid_ = "";
      gamemode_ = "";
      inventory_ = com.google.protobuf.ByteString.EMPTY;
      enderchest_ = com.google.protobuf.ByteString.EMPTY;
      potionEffects_ = com.google.protobuf.ByteString.EMPTY;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserTransferPayload.internal_static_UserConnectServerPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserTransferPayload.internal_static_UserConnectServerPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserTransferPayload.UserConnectServerPayload.class, UserTransferPayload.UserConnectServerPayload.Builder.class);
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SERVERID_FIELD_NUMBER = 2;
    private int serverId_ = 0;
    /**
     * <code>int32 serverId = 2;</code>
     * @return The serverId.
     */
    @java.lang.Override
    public int getServerId() {
      return serverId_;
    }

    public static final int LOCATION_FIELD_NUMBER = 3;
    private UserTransferPayload.Location location_;
    /**
     * <code>.Location location = 3;</code>
     * @return Whether the location field is set.
     */
    @java.lang.Override
    public boolean hasLocation() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.Location location = 3;</code>
     * @return The location.
     */
    @java.lang.Override
    public UserTransferPayload.Location getLocation() {
      return location_ == null ? UserTransferPayload.Location.getDefaultInstance() : location_;
    }
    /**
     * <code>.Location location = 3;</code>
     */
    @java.lang.Override
    public UserTransferPayload.LocationOrBuilder getLocationOrBuilder() {
      return location_ == null ? UserTransferPayload.Location.getDefaultInstance() : location_;
    }

    public static final int GAMEMODE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object gamemode_ = "";
    /**
     * <code>string gamemode = 4;</code>
     * @return The gamemode.
     */
    @java.lang.Override
    public java.lang.String getGamemode() {
      java.lang.Object ref = gamemode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        gamemode_ = s;
        return s;
      }
    }
    /**
     * <code>string gamemode = 4;</code>
     * @return The bytes for gamemode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getGamemodeBytes() {
      java.lang.Object ref = gamemode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        gamemode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SLOT_FIELD_NUMBER = 5;
    private int slot_ = 0;
    /**
     * <code>int32 slot = 5;</code>
     * @return The slot.
     */
    @java.lang.Override
    public int getSlot() {
      return slot_;
    }

    public static final int FOOD_FIELD_NUMBER = 6;
    private int food_ = 0;
    /**
     * <code>int32 food = 6;</code>
     * @return The food.
     */
    @java.lang.Override
    public int getFood() {
      return food_;
    }

    public static final int HEALTH_FIELD_NUMBER = 7;
    private int health_ = 0;
    /**
     * <code>int32 health = 7;</code>
     * @return The health.
     */
    @java.lang.Override
    public int getHealth() {
      return health_;
    }

    public static final int INVENTORY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString inventory_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes inventory = 8;</code>
     * @return The inventory.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getInventory() {
      return inventory_;
    }

    public static final int ENDERCHEST_FIELD_NUMBER = 9;
    private com.google.protobuf.ByteString enderchest_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes enderchest = 9;</code>
     * @return The enderchest.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getEnderchest() {
      return enderchest_;
    }

    public static final int POTIONEFFECTS_FIELD_NUMBER = 10;
    private com.google.protobuf.ByteString potionEffects_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes potionEffects = 10;</code>
     * @return The potionEffects.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getPotionEffects() {
      return potionEffects_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, uuid_);
      }
      if (serverId_ != 0) {
        output.writeInt32(2, serverId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(3, getLocation());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gamemode_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, gamemode_);
      }
      if (slot_ != 0) {
        output.writeInt32(5, slot_);
      }
      if (food_ != 0) {
        output.writeInt32(6, food_);
      }
      if (health_ != 0) {
        output.writeInt32(7, health_);
      }
      if (!inventory_.isEmpty()) {
        output.writeBytes(8, inventory_);
      }
      if (!enderchest_.isEmpty()) {
        output.writeBytes(9, enderchest_);
      }
      if (!potionEffects_.isEmpty()) {
        output.writeBytes(10, potionEffects_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uuid_);
      }
      if (serverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, serverId_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getLocation());
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(gamemode_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, gamemode_);
      }
      if (slot_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, slot_);
      }
      if (food_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, food_);
      }
      if (health_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, health_);
      }
      if (!inventory_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, inventory_);
      }
      if (!enderchest_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(9, enderchest_);
      }
      if (!potionEffects_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10, potionEffects_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserTransferPayload.UserConnectServerPayload)) {
        return super.equals(obj);
      }
      UserTransferPayload.UserConnectServerPayload other = (UserTransferPayload.UserConnectServerPayload) obj;

      if (!getUuid()
          .equals(other.getUuid())) return false;
      if (getServerId()
          != other.getServerId()) return false;
      if (hasLocation() != other.hasLocation()) return false;
      if (hasLocation()) {
        if (!getLocation()
            .equals(other.getLocation())) return false;
      }
      if (!getGamemode()
          .equals(other.getGamemode())) return false;
      if (getSlot()
          != other.getSlot()) return false;
      if (getFood()
          != other.getFood()) return false;
      if (getHealth()
          != other.getHealth()) return false;
      if (!getInventory()
          .equals(other.getInventory())) return false;
      if (!getEnderchest()
          .equals(other.getEnderchest())) return false;
      if (!getPotionEffects()
          .equals(other.getPotionEffects())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId();
      if (hasLocation()) {
        hash = (37 * hash) + LOCATION_FIELD_NUMBER;
        hash = (53 * hash) + getLocation().hashCode();
      }
      hash = (37 * hash) + GAMEMODE_FIELD_NUMBER;
      hash = (53 * hash) + getGamemode().hashCode();
      hash = (37 * hash) + SLOT_FIELD_NUMBER;
      hash = (53 * hash) + getSlot();
      hash = (37 * hash) + FOOD_FIELD_NUMBER;
      hash = (53 * hash) + getFood();
      hash = (37 * hash) + HEALTH_FIELD_NUMBER;
      hash = (53 * hash) + getHealth();
      hash = (37 * hash) + INVENTORY_FIELD_NUMBER;
      hash = (53 * hash) + getInventory().hashCode();
      hash = (37 * hash) + ENDERCHEST_FIELD_NUMBER;
      hash = (53 * hash) + getEnderchest().hashCode();
      hash = (37 * hash) + POTIONEFFECTS_FIELD_NUMBER;
      hash = (53 * hash) + getPotionEffects().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserTransferPayload.UserConnectServerPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserTransferPayload.UserConnectServerPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserTransferPayload.UserConnectServerPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserTransferPayload.UserConnectServerPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserTransferPayload.UserConnectServerPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserTransferPayload.UserConnectServerPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserTransferPayload.UserConnectServerPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static UserTransferPayload.UserConnectServerPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserTransferPayload.UserConnectServerPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static UserTransferPayload.UserConnectServerPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserTransferPayload.UserConnectServerPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static UserTransferPayload.UserConnectServerPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserTransferPayload.UserConnectServerPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code UserConnectServerPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:UserConnectServerPayload)
        UserTransferPayload.UserConnectServerPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserTransferPayload.internal_static_UserConnectServerPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserTransferPayload.internal_static_UserConnectServerPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserTransferPayload.UserConnectServerPayload.class, UserTransferPayload.UserConnectServerPayload.Builder.class);
      }

      // Construct using UserTransferPayload.UserConnectServerPayload.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage
                .alwaysUseFieldBuilders) {
          getLocationFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        uuid_ = "";
        serverId_ = 0;
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        gamemode_ = "";
        slot_ = 0;
        food_ = 0;
        health_ = 0;
        inventory_ = com.google.protobuf.ByteString.EMPTY;
        enderchest_ = com.google.protobuf.ByteString.EMPTY;
        potionEffects_ = com.google.protobuf.ByteString.EMPTY;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserTransferPayload.internal_static_UserConnectServerPayload_descriptor;
      }

      @java.lang.Override
      public UserTransferPayload.UserConnectServerPayload getDefaultInstanceForType() {
        return UserTransferPayload.UserConnectServerPayload.getDefaultInstance();
      }

      @java.lang.Override
      public UserTransferPayload.UserConnectServerPayload build() {
        UserTransferPayload.UserConnectServerPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public UserTransferPayload.UserConnectServerPayload buildPartial() {
        UserTransferPayload.UserConnectServerPayload result = new UserTransferPayload.UserConnectServerPayload(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(UserTransferPayload.UserConnectServerPayload result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.uuid_ = uuid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.serverId_ = serverId_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.location_ = locationBuilder_ == null
              ? location_
              : locationBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.gamemode_ = gamemode_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.slot_ = slot_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.food_ = food_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.health_ = health_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.inventory_ = inventory_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          result.enderchest_ = enderchest_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          result.potionEffects_ = potionEffects_;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserTransferPayload.UserConnectServerPayload) {
          return mergeFrom((UserTransferPayload.UserConnectServerPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserTransferPayload.UserConnectServerPayload other) {
        if (other == UserTransferPayload.UserConnectServerPayload.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getServerId() != 0) {
          setServerId(other.getServerId());
        }
        if (other.hasLocation()) {
          mergeLocation(other.getLocation());
        }
        if (!other.getGamemode().isEmpty()) {
          gamemode_ = other.gamemode_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (other.getSlot() != 0) {
          setSlot(other.getSlot());
        }
        if (other.getFood() != 0) {
          setFood(other.getFood());
        }
        if (other.getHealth() != 0) {
          setHealth(other.getHealth());
        }
        if (other.getInventory() != com.google.protobuf.ByteString.EMPTY) {
          setInventory(other.getInventory());
        }
        if (other.getEnderchest() != com.google.protobuf.ByteString.EMPTY) {
          setEnderchest(other.getEnderchest());
        }
        if (other.getPotionEffects() != com.google.protobuf.ByteString.EMPTY) {
          setPotionEffects(other.getPotionEffects());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                uuid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                serverId_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                input.readMessage(
                    getLocationFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                gamemode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 40: {
                slot_ = input.readInt32();
                bitField0_ |= 0x00000010;
                break;
              } // case 40
              case 48: {
                food_ = input.readInt32();
                bitField0_ |= 0x00000020;
                break;
              } // case 48
              case 56: {
                health_ = input.readInt32();
                bitField0_ |= 0x00000040;
                break;
              } // case 56
              case 66: {
                inventory_ = input.readBytes();
                bitField0_ |= 0x00000080;
                break;
              } // case 66
              case 74: {
                enderchest_ = input.readBytes();
                bitField0_ |= 0x00000100;
                break;
              } // case 74
              case 82: {
                potionEffects_ = input.readBytes();
                bitField0_ |= 0x00000200;
                break;
              } // case 82
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <code>string uuid = 1;</code>
       * @return The uuid.
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        uuid_ = getDefaultInstance().getUuid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int serverId_ ;
      /**
       * <code>int32 serverId = 2;</code>
       * @return The serverId.
       */
      @java.lang.Override
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>int32 serverId = 2;</code>
       * @param value The serverId to set.
       * @return This builder for chaining.
       */
      public Builder setServerId(int value) {

        serverId_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 serverId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        serverId_ = 0;
        onChanged();
        return this;
      }

      private UserTransferPayload.Location location_;
      private com.google.protobuf.SingleFieldBuilder<
          UserTransferPayload.Location, UserTransferPayload.Location.Builder, UserTransferPayload.LocationOrBuilder> locationBuilder_;
      /**
       * <code>.Location location = 3;</code>
       * @return Whether the location field is set.
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>.Location location = 3;</code>
       * @return The location.
       */
      public UserTransferPayload.Location getLocation() {
        if (locationBuilder_ == null) {
          return location_ == null ? UserTransferPayload.Location.getDefaultInstance() : location_;
        } else {
          return locationBuilder_.getMessage();
        }
      }
      /**
       * <code>.Location location = 3;</code>
       */
      public Builder setLocation(UserTransferPayload.Location value) {
        if (locationBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          location_ = value;
        } else {
          locationBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.Location location = 3;</code>
       */
      public Builder setLocation(
          UserTransferPayload.Location.Builder builderForValue) {
        if (locationBuilder_ == null) {
          location_ = builderForValue.build();
        } else {
          locationBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>.Location location = 3;</code>
       */
      public Builder mergeLocation(UserTransferPayload.Location value) {
        if (locationBuilder_ == null) {
          if (((bitField0_ & 0x00000004) != 0) &&
            location_ != null &&
            location_ != UserTransferPayload.Location.getDefaultInstance()) {
            getLocationBuilder().mergeFrom(value);
          } else {
            location_ = value;
          }
        } else {
          locationBuilder_.mergeFrom(value);
        }
        if (location_ != null) {
          bitField0_ |= 0x00000004;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.Location location = 3;</code>
       */
      public Builder clearLocation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        location_ = null;
        if (locationBuilder_ != null) {
          locationBuilder_.dispose();
          locationBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.Location location = 3;</code>
       */
      public UserTransferPayload.Location.Builder getLocationBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getLocationFieldBuilder().getBuilder();
      }
      /**
       * <code>.Location location = 3;</code>
       */
      public UserTransferPayload.LocationOrBuilder getLocationOrBuilder() {
        if (locationBuilder_ != null) {
          return locationBuilder_.getMessageOrBuilder();
        } else {
          return location_ == null ?
              UserTransferPayload.Location.getDefaultInstance() : location_;
        }
      }
      /**
       * <code>.Location location = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          UserTransferPayload.Location, UserTransferPayload.Location.Builder, UserTransferPayload.LocationOrBuilder> 
          getLocationFieldBuilder() {
        if (locationBuilder_ == null) {
          locationBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              UserTransferPayload.Location, UserTransferPayload.Location.Builder, UserTransferPayload.LocationOrBuilder>(
                  getLocation(),
                  getParentForChildren(),
                  isClean());
          location_ = null;
        }
        return locationBuilder_;
      }

      private java.lang.Object gamemode_ = "";
      /**
       * <code>string gamemode = 4;</code>
       * @return The gamemode.
       */
      public java.lang.String getGamemode() {
        java.lang.Object ref = gamemode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          gamemode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string gamemode = 4;</code>
       * @return The bytes for gamemode.
       */
      public com.google.protobuf.ByteString
          getGamemodeBytes() {
        java.lang.Object ref = gamemode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          gamemode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string gamemode = 4;</code>
       * @param value The gamemode to set.
       * @return This builder for chaining.
       */
      public Builder setGamemode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        gamemode_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string gamemode = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearGamemode() {
        gamemode_ = getDefaultInstance().getGamemode();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string gamemode = 4;</code>
       * @param value The bytes for gamemode to set.
       * @return This builder for chaining.
       */
      public Builder setGamemodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        gamemode_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private int slot_ ;
      /**
       * <code>int32 slot = 5;</code>
       * @return The slot.
       */
      @java.lang.Override
      public int getSlot() {
        return slot_;
      }
      /**
       * <code>int32 slot = 5;</code>
       * @param value The slot to set.
       * @return This builder for chaining.
       */
      public Builder setSlot(int value) {

        slot_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>int32 slot = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSlot() {
        bitField0_ = (bitField0_ & ~0x00000010);
        slot_ = 0;
        onChanged();
        return this;
      }

      private int food_ ;
      /**
       * <code>int32 food = 6;</code>
       * @return The food.
       */
      @java.lang.Override
      public int getFood() {
        return food_;
      }
      /**
       * <code>int32 food = 6;</code>
       * @param value The food to set.
       * @return This builder for chaining.
       */
      public Builder setFood(int value) {

        food_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>int32 food = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearFood() {
        bitField0_ = (bitField0_ & ~0x00000020);
        food_ = 0;
        onChanged();
        return this;
      }

      private int health_ ;
      /**
       * <code>int32 health = 7;</code>
       * @return The health.
       */
      @java.lang.Override
      public int getHealth() {
        return health_;
      }
      /**
       * <code>int32 health = 7;</code>
       * @param value The health to set.
       * @return This builder for chaining.
       */
      public Builder setHealth(int value) {

        health_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>int32 health = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearHealth() {
        bitField0_ = (bitField0_ & ~0x00000040);
        health_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString inventory_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes inventory = 8;</code>
       * @return The inventory.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getInventory() {
        return inventory_;
      }
      /**
       * <code>bytes inventory = 8;</code>
       * @param value The inventory to set.
       * @return This builder for chaining.
       */
      public Builder setInventory(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        inventory_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>bytes inventory = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearInventory() {
        bitField0_ = (bitField0_ & ~0x00000080);
        inventory_ = getDefaultInstance().getInventory();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString enderchest_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes enderchest = 9;</code>
       * @return The enderchest.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getEnderchest() {
        return enderchest_;
      }
      /**
       * <code>bytes enderchest = 9;</code>
       * @param value The enderchest to set.
       * @return This builder for chaining.
       */
      public Builder setEnderchest(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        enderchest_ = value;
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>bytes enderchest = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearEnderchest() {
        bitField0_ = (bitField0_ & ~0x00000100);
        enderchest_ = getDefaultInstance().getEnderchest();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString potionEffects_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes potionEffects = 10;</code>
       * @return The potionEffects.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getPotionEffects() {
        return potionEffects_;
      }
      /**
       * <code>bytes potionEffects = 10;</code>
       * @param value The potionEffects to set.
       * @return This builder for chaining.
       */
      public Builder setPotionEffects(com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        potionEffects_ = value;
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>bytes potionEffects = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearPotionEffects() {
        bitField0_ = (bitField0_ & ~0x00000200);
        potionEffects_ = getDefaultInstance().getPotionEffects();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:UserConnectServerPayload)
    }

    // @@protoc_insertion_point(class_scope:UserConnectServerPayload)
    private static final UserTransferPayload.UserConnectServerPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserTransferPayload.UserConnectServerPayload();
    }

    public static UserTransferPayload.UserConnectServerPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserConnectServerPayload>
        PARSER = new com.google.protobuf.AbstractParser<UserConnectServerPayload>() {
      @java.lang.Override
      public UserConnectServerPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<UserConnectServerPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserConnectServerPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public UserTransferPayload.UserConnectServerPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LocationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Location)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>double x = 2;</code>
     * @return The x.
     */
    double getX();

    /**
     * <code>double y = 3;</code>
     * @return The y.
     */
    double getY();

    /**
     * <code>double z = 4;</code>
     * @return The z.
     */
    double getZ();

    /**
     * <code>optional float yaw = 5;</code>
     * @return Whether the yaw field is set.
     */
    boolean hasYaw();
    /**
     * <code>optional float yaw = 5;</code>
     * @return The yaw.
     */
    float getYaw();

    /**
     * <code>optional float pitch = 6;</code>
     * @return Whether the pitch field is set.
     */
    boolean hasPitch();
    /**
     * <code>optional float pitch = 6;</code>
     * @return The pitch.
     */
    float getPitch();
  }
  /**
   * Protobuf type {@code Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Location)
      LocationOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 26,
        /* patch= */ 0,
        /* suffix= */ "-rc2",
        Location.class.getName());
    }
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Location() {
      name_ = "";
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return UserTransferPayload.internal_static_Location_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return UserTransferPayload.internal_static_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              UserTransferPayload.Location.class, UserTransferPayload.Location.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int X_FIELD_NUMBER = 2;
    private double x_ = 0D;
    /**
     * <code>double x = 2;</code>
     * @return The x.
     */
    @java.lang.Override
    public double getX() {
      return x_;
    }

    public static final int Y_FIELD_NUMBER = 3;
    private double y_ = 0D;
    /**
     * <code>double y = 3;</code>
     * @return The y.
     */
    @java.lang.Override
    public double getY() {
      return y_;
    }

    public static final int Z_FIELD_NUMBER = 4;
    private double z_ = 0D;
    /**
     * <code>double z = 4;</code>
     * @return The z.
     */
    @java.lang.Override
    public double getZ() {
      return z_;
    }

    public static final int YAW_FIELD_NUMBER = 5;
    private float yaw_ = 0F;
    /**
     * <code>optional float yaw = 5;</code>
     * @return Whether the yaw field is set.
     */
    @java.lang.Override
    public boolean hasYaw() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>optional float yaw = 5;</code>
     * @return The yaw.
     */
    @java.lang.Override
    public float getYaw() {
      return yaw_;
    }

    public static final int PITCH_FIELD_NUMBER = 6;
    private float pitch_ = 0F;
    /**
     * <code>optional float pitch = 6;</code>
     * @return Whether the pitch field is set.
     */
    @java.lang.Override
    public boolean hasPitch() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>optional float pitch = 6;</code>
     * @return The pitch.
     */
    @java.lang.Override
    public float getPitch() {
      return pitch_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
      }
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        output.writeDouble(2, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        output.writeDouble(3, y_);
      }
      if (java.lang.Double.doubleToRawLongBits(z_) != 0) {
        output.writeDouble(4, z_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeFloat(5, yaw_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeFloat(6, pitch_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
      }
      if (java.lang.Double.doubleToRawLongBits(x_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, x_);
      }
      if (java.lang.Double.doubleToRawLongBits(y_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, y_);
      }
      if (java.lang.Double.doubleToRawLongBits(z_) != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, z_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, yaw_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(6, pitch_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof UserTransferPayload.Location)) {
        return super.equals(obj);
      }
      UserTransferPayload.Location other = (UserTransferPayload.Location) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (java.lang.Double.doubleToLongBits(getX())
          != java.lang.Double.doubleToLongBits(
              other.getX())) return false;
      if (java.lang.Double.doubleToLongBits(getY())
          != java.lang.Double.doubleToLongBits(
              other.getY())) return false;
      if (java.lang.Double.doubleToLongBits(getZ())
          != java.lang.Double.doubleToLongBits(
              other.getZ())) return false;
      if (hasYaw() != other.hasYaw()) return false;
      if (hasYaw()) {
        if (java.lang.Float.floatToIntBits(getYaw())
            != java.lang.Float.floatToIntBits(
                other.getYaw())) return false;
      }
      if (hasPitch() != other.hasPitch()) return false;
      if (hasPitch()) {
        if (java.lang.Float.floatToIntBits(getPitch())
            != java.lang.Float.floatToIntBits(
                other.getPitch())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + X_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getX()));
      hash = (37 * hash) + Y_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getY()));
      hash = (37 * hash) + Z_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getZ()));
      if (hasYaw()) {
        hash = (37 * hash) + YAW_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getYaw());
      }
      if (hasPitch()) {
        hash = (37 * hash) + PITCH_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getPitch());
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static UserTransferPayload.Location parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserTransferPayload.Location parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserTransferPayload.Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserTransferPayload.Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserTransferPayload.Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static UserTransferPayload.Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static UserTransferPayload.Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static UserTransferPayload.Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static UserTransferPayload.Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static UserTransferPayload.Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static UserTransferPayload.Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static UserTransferPayload.Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(UserTransferPayload.Location prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Location)
        UserTransferPayload.LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return UserTransferPayload.internal_static_Location_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return UserTransferPayload.internal_static_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                UserTransferPayload.Location.class, UserTransferPayload.Location.Builder.class);
      }

      // Construct using UserTransferPayload.Location.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        x_ = 0D;
        y_ = 0D;
        z_ = 0D;
        yaw_ = 0F;
        pitch_ = 0F;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return UserTransferPayload.internal_static_Location_descriptor;
      }

      @java.lang.Override
      public UserTransferPayload.Location getDefaultInstanceForType() {
        return UserTransferPayload.Location.getDefaultInstance();
      }

      @java.lang.Override
      public UserTransferPayload.Location build() {
        UserTransferPayload.Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public UserTransferPayload.Location buildPartial() {
        UserTransferPayload.Location result = new UserTransferPayload.Location(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(UserTransferPayload.Location result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.x_ = x_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.y_ = y_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.z_ = z_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.yaw_ = yaw_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.pitch_ = pitch_;
          to_bitField0_ |= 0x00000002;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof UserTransferPayload.Location) {
          return mergeFrom((UserTransferPayload.Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(UserTransferPayload.Location other) {
        if (other == UserTransferPayload.Location.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getX() != 0D) {
          setX(other.getX());
        }
        if (other.getY() != 0D) {
          setY(other.getY());
        }
        if (other.getZ() != 0D) {
          setZ(other.getZ());
        }
        if (other.hasYaw()) {
          setYaw(other.getYaw());
        }
        if (other.hasPitch()) {
          setPitch(other.getPitch());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 17: {
                x_ = input.readDouble();
                bitField0_ |= 0x00000002;
                break;
              } // case 17
              case 25: {
                y_ = input.readDouble();
                bitField0_ |= 0x00000004;
                break;
              } // case 25
              case 33: {
                z_ = input.readDouble();
                bitField0_ |= 0x00000008;
                break;
              } // case 33
              case 45: {
                yaw_ = input.readFloat();
                bitField0_ |= 0x00000010;
                break;
              } // case 45
              case 53: {
                pitch_ = input.readFloat();
                bitField0_ |= 0x00000020;
                break;
              } // case 53
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private double x_ ;
      /**
       * <code>double x = 2;</code>
       * @return The x.
       */
      @java.lang.Override
      public double getX() {
        return x_;
      }
      /**
       * <code>double x = 2;</code>
       * @param value The x to set.
       * @return This builder for chaining.
       */
      public Builder setX(double value) {

        x_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>double x = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearX() {
        bitField0_ = (bitField0_ & ~0x00000002);
        x_ = 0D;
        onChanged();
        return this;
      }

      private double y_ ;
      /**
       * <code>double y = 3;</code>
       * @return The y.
       */
      @java.lang.Override
      public double getY() {
        return y_;
      }
      /**
       * <code>double y = 3;</code>
       * @param value The y to set.
       * @return This builder for chaining.
       */
      public Builder setY(double value) {

        y_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>double y = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearY() {
        bitField0_ = (bitField0_ & ~0x00000004);
        y_ = 0D;
        onChanged();
        return this;
      }

      private double z_ ;
      /**
       * <code>double z = 4;</code>
       * @return The z.
       */
      @java.lang.Override
      public double getZ() {
        return z_;
      }
      /**
       * <code>double z = 4;</code>
       * @param value The z to set.
       * @return This builder for chaining.
       */
      public Builder setZ(double value) {

        z_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>double z = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearZ() {
        bitField0_ = (bitField0_ & ~0x00000008);
        z_ = 0D;
        onChanged();
        return this;
      }

      private float yaw_ ;
      /**
       * <code>optional float yaw = 5;</code>
       * @return Whether the yaw field is set.
       */
      @java.lang.Override
      public boolean hasYaw() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>optional float yaw = 5;</code>
       * @return The yaw.
       */
      @java.lang.Override
      public float getYaw() {
        return yaw_;
      }
      /**
       * <code>optional float yaw = 5;</code>
       * @param value The yaw to set.
       * @return This builder for chaining.
       */
      public Builder setYaw(float value) {

        yaw_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>optional float yaw = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearYaw() {
        bitField0_ = (bitField0_ & ~0x00000010);
        yaw_ = 0F;
        onChanged();
        return this;
      }

      private float pitch_ ;
      /**
       * <code>optional float pitch = 6;</code>
       * @return Whether the pitch field is set.
       */
      @java.lang.Override
      public boolean hasPitch() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional float pitch = 6;</code>
       * @return The pitch.
       */
      @java.lang.Override
      public float getPitch() {
        return pitch_;
      }
      /**
       * <code>optional float pitch = 6;</code>
       * @param value The pitch to set.
       * @return This builder for chaining.
       */
      public Builder setPitch(float value) {

        pitch_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>optional float pitch = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearPitch() {
        bitField0_ = (bitField0_ & ~0x00000020);
        pitch_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Location)
    }

    // @@protoc_insertion_point(class_scope:Location)
    private static final UserTransferPayload.Location DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new UserTransferPayload.Location();
    }

    public static UserTransferPayload.Location getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Location>
        PARSER = new com.google.protobuf.AbstractParser<Location>() {
      @java.lang.Override
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Location> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public UserTransferPayload.Location getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_UserConnectServerPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_UserConnectServerPayload_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Location_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031UserTransferPayload.proto\"\323\001\n\030UserConn" +
      "ectServerPayload\022\014\n\004uuid\030\001 \001(\t\022\020\n\010server" +
      "Id\030\002 \001(\005\022\033\n\010location\030\003 \001(\0132\t.Location\022\020\n" +
      "\010gamemode\030\004 \001(\t\022\014\n\004slot\030\005 \001(\005\022\014\n\004food\030\006 " +
      "\001(\005\022\016\n\006health\030\007 \001(\005\022\021\n\tinventory\030\010 \001(\014\022\022" +
      "\n\nenderchest\030\t \001(\014\022\025\n\rpotionEffects\030\n \001(" +
      "\014\"q\n\010Location\022\014\n\004name\030\001 \001(\t\022\t\n\001x\030\002 \001(\001\022\t" +
      "\n\001y\030\003 \001(\001\022\t\n\001z\030\004 \001(\001\022\020\n\003yaw\030\005 \001(\002H\000\210\001\001\022\022" +
      "\n\005pitch\030\006 \001(\002H\001\210\001\001B\006\n\004_yawB\010\n\006_pitchb\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_UserConnectServerPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_UserConnectServerPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_UserConnectServerPayload_descriptor,
        new java.lang.String[] { "Uuid", "ServerId", "Location", "Gamemode", "Slot", "Food", "Health", "Inventory", "Enderchest", "PotionEffects", });
    internal_static_Location_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Location_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Location_descriptor,
        new java.lang.String[] { "Name", "X", "Y", "Z", "Yaw", "Pitch", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
