package usd.jedzius.crispychannels.protocol.payload;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: crispychannels-protobuf/ClientUpdatePayloadProto.proto

// Protobuf Java Version: 3.25.2
public final class ClientUpdatePayload {
  private ClientUpdatePayload() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ClientUpdateInfoPayloadOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ClientUpdateInfoPayload)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 online = 2;</code>
     * @return The online.
     */
    int getOnline();

    /**
     * <code>int32 max = 3;</code>
     * @return The max.
     */
    int getMax();

    /**
     * <code>string last_update = 4;</code>
     * @return The lastUpdate.
     */
    java.lang.String getLastUpdate();
    /**
     * <code>string last_update = 4;</code>
     * @return The bytes for lastUpdate.
     */
    com.google.protobuf.ByteString
        getLastUpdateBytes();
  }
  /**
   * Protobuf type {@code ClientUpdateInfoPayload}
   */
  public static final class ClientUpdateInfoPayload extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ClientUpdateInfoPayload)
      ClientUpdateInfoPayloadOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ClientUpdateInfoPayload.newBuilder() to construct.
    private ClientUpdateInfoPayload(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ClientUpdateInfoPayload() {
      lastUpdate_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ClientUpdateInfoPayload();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ClientUpdatePayload.internal_static_ClientUpdateInfoPayload_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ClientUpdatePayload.internal_static_ClientUpdateInfoPayload_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ClientUpdatePayload.ClientUpdateInfoPayload.class, ClientUpdatePayload.ClientUpdateInfoPayload.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int ONLINE_FIELD_NUMBER = 2;
    private int online_ = 0;
    /**
     * <code>int32 online = 2;</code>
     * @return The online.
     */
    @java.lang.Override
    public int getOnline() {
      return online_;
    }

    public static final int MAX_FIELD_NUMBER = 3;
    private int max_ = 0;
    /**
     * <code>int32 max = 3;</code>
     * @return The max.
     */
    @java.lang.Override
    public int getMax() {
      return max_;
    }

    public static final int LAST_UPDATE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object lastUpdate_ = "";
    /**
     * <code>string last_update = 4;</code>
     * @return The lastUpdate.
     */
    @java.lang.Override
    public java.lang.String getLastUpdate() {
      java.lang.Object ref = lastUpdate_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastUpdate_ = s;
        return s;
      }
    }
    /**
     * <code>string last_update = 4;</code>
     * @return The bytes for lastUpdate.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getLastUpdateBytes() {
      java.lang.Object ref = lastUpdate_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastUpdate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (online_ != 0) {
        output.writeInt32(2, online_);
      }
      if (max_ != 0) {
        output.writeInt32(3, max_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastUpdate_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, lastUpdate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (online_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, online_);
      }
      if (max_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, max_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(lastUpdate_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, lastUpdate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ClientUpdatePayload.ClientUpdateInfoPayload)) {
        return super.equals(obj);
      }
      ClientUpdatePayload.ClientUpdateInfoPayload other = (ClientUpdatePayload.ClientUpdateInfoPayload) obj;

      if (getId()
          != other.getId()) return false;
      if (getOnline()
          != other.getOnline()) return false;
      if (getMax()
          != other.getMax()) return false;
      if (!getLastUpdate()
          .equals(other.getLastUpdate())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + ONLINE_FIELD_NUMBER;
      hash = (53 * hash) + getOnline();
      hash = (37 * hash) + MAX_FIELD_NUMBER;
      hash = (53 * hash) + getMax();
      hash = (37 * hash) + LAST_UPDATE_FIELD_NUMBER;
      hash = (53 * hash) + getLastUpdate().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ClientUpdatePayload.ClientUpdateInfoPayload parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientUpdatePayload.ClientUpdateInfoPayload parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientUpdatePayload.ClientUpdateInfoPayload parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientUpdatePayload.ClientUpdateInfoPayload parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientUpdatePayload.ClientUpdateInfoPayload parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ClientUpdatePayload.ClientUpdateInfoPayload parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ClientUpdatePayload.ClientUpdateInfoPayload parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientUpdatePayload.ClientUpdateInfoPayload parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static ClientUpdatePayload.ClientUpdateInfoPayload parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static ClientUpdatePayload.ClientUpdateInfoPayload parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ClientUpdatePayload.ClientUpdateInfoPayload parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ClientUpdatePayload.ClientUpdateInfoPayload parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ClientUpdatePayload.ClientUpdateInfoPayload prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ClientUpdateInfoPayload}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ClientUpdateInfoPayload)
        ClientUpdatePayload.ClientUpdateInfoPayloadOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ClientUpdatePayload.internal_static_ClientUpdateInfoPayload_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ClientUpdatePayload.internal_static_ClientUpdateInfoPayload_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ClientUpdatePayload.ClientUpdateInfoPayload.class, ClientUpdatePayload.ClientUpdateInfoPayload.Builder.class);
      }

      // Construct using ClientUpdatePayload.ClientUpdateInfoPayload.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        online_ = 0;
        max_ = 0;
        lastUpdate_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ClientUpdatePayload.internal_static_ClientUpdateInfoPayload_descriptor;
      }

      @java.lang.Override
      public ClientUpdatePayload.ClientUpdateInfoPayload getDefaultInstanceForType() {
        return ClientUpdatePayload.ClientUpdateInfoPayload.getDefaultInstance();
      }

      @java.lang.Override
      public ClientUpdatePayload.ClientUpdateInfoPayload build() {
        ClientUpdatePayload.ClientUpdateInfoPayload result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ClientUpdatePayload.ClientUpdateInfoPayload buildPartial() {
        ClientUpdatePayload.ClientUpdateInfoPayload result = new ClientUpdatePayload.ClientUpdateInfoPayload(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(ClientUpdatePayload.ClientUpdateInfoPayload result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.online_ = online_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.max_ = max_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.lastUpdate_ = lastUpdate_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ClientUpdatePayload.ClientUpdateInfoPayload) {
          return mergeFrom((ClientUpdatePayload.ClientUpdateInfoPayload)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ClientUpdatePayload.ClientUpdateInfoPayload other) {
        if (other == ClientUpdatePayload.ClientUpdateInfoPayload.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.getOnline() != 0) {
          setOnline(other.getOnline());
        }
        if (other.getMax() != 0) {
          setMax(other.getMax());
        }
        if (!other.getLastUpdate().isEmpty()) {
          lastUpdate_ = other.lastUpdate_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 16: {
                online_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 24: {
                max_ = input.readInt32();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                lastUpdate_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int online_ ;
      /**
       * <code>int32 online = 2;</code>
       * @return The online.
       */
      @java.lang.Override
      public int getOnline() {
        return online_;
      }
      /**
       * <code>int32 online = 2;</code>
       * @param value The online to set.
       * @return This builder for chaining.
       */
      public Builder setOnline(int value) {

        online_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 online = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearOnline() {
        bitField0_ = (bitField0_ & ~0x00000002);
        online_ = 0;
        onChanged();
        return this;
      }

      private int max_ ;
      /**
       * <code>int32 max = 3;</code>
       * @return The max.
       */
      @java.lang.Override
      public int getMax() {
        return max_;
      }
      /**
       * <code>int32 max = 3;</code>
       * @param value The max to set.
       * @return This builder for chaining.
       */
      public Builder setMax(int value) {

        max_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>int32 max = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMax() {
        bitField0_ = (bitField0_ & ~0x00000004);
        max_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object lastUpdate_ = "";
      /**
       * <code>string last_update = 4;</code>
       * @return The lastUpdate.
       */
      public java.lang.String getLastUpdate() {
        java.lang.Object ref = lastUpdate_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          lastUpdate_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string last_update = 4;</code>
       * @return The bytes for lastUpdate.
       */
      public com.google.protobuf.ByteString
          getLastUpdateBytes() {
        java.lang.Object ref = lastUpdate_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastUpdate_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string last_update = 4;</code>
       * @param value The lastUpdate to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdate(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        lastUpdate_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string last_update = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdate() {
        lastUpdate_ = getDefaultInstance().getLastUpdate();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string last_update = 4;</code>
       * @param value The bytes for lastUpdate to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        lastUpdate_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ClientUpdateInfoPayload)
    }

    // @@protoc_insertion_point(class_scope:ClientUpdateInfoPayload)
    private static final ClientUpdatePayload.ClientUpdateInfoPayload DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ClientUpdatePayload.ClientUpdateInfoPayload();
    }

    public static ClientUpdatePayload.ClientUpdateInfoPayload getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ClientUpdateInfoPayload>
        PARSER = new com.google.protobuf.AbstractParser<ClientUpdateInfoPayload>() {
      @java.lang.Override
      public ClientUpdateInfoPayload parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<ClientUpdateInfoPayload> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ClientUpdateInfoPayload> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ClientUpdatePayload.ClientUpdateInfoPayload getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClientUpdateInfoPayload_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClientUpdateInfoPayload_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n6crispychannels-protobuf/ClientUpdatePa" +
      "yloadProto.proto\"W\n\027ClientUpdateInfoPayl" +
      "oad\022\n\n\002id\030\001 \001(\005\022\016\n\006online\030\002 \001(\005\022\013\n\003max\030\003" +
      " \001(\005\022\023\n\013last_update\030\004 \001(\tB\025B\023ClientUpdat" +
      "ePayloadb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ClientUpdateInfoPayload_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ClientUpdateInfoPayload_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClientUpdateInfoPayload_descriptor,
        new java.lang.String[] { "Id", "Online", "Max", "LastUpdate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
